#!/usr/bin/env bash
# configure Nginx so that its HTTP response contains a custom header
# (on web-01 and web-02)
# The name of the custom HTTP header must be X-Served-By
# The value of the custom HTTP header must be the hostname of the server NGINX
# is running on.
sudo apt-get update
sudo apt-get -y install nginx

# configure firewall to allow request through port 80
sudo ufw allow 'Nginx HTTP'

sudo mkdir -p /var/www/html

# change permissions to allow us to easily create files in this directory
sudo chmod -R 755 /var/www

# create the index page
echo 'Hello World!' | sudo tee /var/www/html/index.html

# create a webpage for error 404
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# code to configure redirect for a single page (redirect_me) and add header to display hostname
string_for_replacement="server_name _;\n\tadd_header X_Served_By \$hostname; \n\trewrite ^\/redirect_me https:\/\/dochine.tech permanent;"
sudo sed -i "s/listen 80 default_server;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# restart the web server after updating the settings
sudo service nginx restart
