#!/usr/bin/env bash
# Configures Nginx with a custom header for both  web-01 and web-02 when an http request is sent 
# The name of the custom HTTP header must be X-Served-By
# The value of the custom HTTP header must be the hostname of the server Nginx is running on(either web-01 or web-02)

#Update system repository
sudo apt-get update

#Install Nginx
sudo apt-get -y install nginx

# configure firewall to allow request through port 80
sudo ufw allow 'Nginx HTTP'

#Create document directory, if not present
sudo mkdir -p /var/www/html

# change permissions to allow easy  creation of files in this directory
sudo chmod -R 755 /var/www

#  create the index html page
echo 'Hello World!' | sudo tee  /var/www/html/index.html

# create a webpage for error 404
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# code to configure redirect for a single page(/redirect_me) and add header to display hostname
string_for_replacement="server_name _;\n\tadd_header X-Served-By \$hostname;\n\trewrite ^\/redirect_me https:\/\/dochine.tech permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# code to configure redirect for 404 error page
string_for_replacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# restart the web server after updating the settings
sudo service nginx restart
