#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02
# Distribute requests using a roundrobin algorithm
# Make sure that HAproxy can be managed via an init script
# Make sure that your servers are configured with the right hostnames:
# [STUDENT_ID]-web-01 and [STUDENT_ID]-web-02. If not, follow this tutorial.

# Install and configure HAProxy on my lb-01 server
sudo apt-get update
apt-get -y install haproxy

# edit config file
server_config=\
"
frontend dochine-frontend
	bind *:80
	mode http
	default_backend samke_backend
backend dochine-backend
	balance roundrobin
	server 252634-web-01 100.25.13.174:80 check
	server 252634-web-02 204.236.223.235:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
