#!/usr/bin/env bash
# Bash script that displays "To infinity and beyond" indefinetely with sleep 2 in between each iteration
# "I am invinvicible" when receiving a SIGTERM signal

trap 'echo "I am invicible!!!"'
SIGTERM
while true
do
	echo "To infinity and beyond"
	sleep 2
done
