#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd
# script should display username, id, Home directory path of the user
# must use while loop

file="/etc/passwd"
while IFS= read -r line
do
	echo "$line" | cut -d":" -f1, 3, 6
done < "$myfile"
