#!/usr/bin/env bash
# Bash script that displays visitors Ip address along with http status code
# and parses apache log files in list format

file="apache-access.log"
awk -F' ' '{ print $1, $9}' $file
