#!/usr/bin/env bash
# This script is usinf while loop to display string "Best School" 10 times
string="Best School"
num_times=10
counter=1
while (($counter <= $num_times)); do
echo "$string"
((counter +=1))
done
