#!/usr/bin/env bash
# Bash script that displays 12 hours and 59 minutes
# displays hours from 0 to 12
# displays minutes from 1 to 59 and only use while loop

hour=0

while [ $hour -le 12 ]
do
	echo "Hour: $hour"
	minute=1
	while [ $minute -le 59 ]
	do
		echo "$minute"
		((minute++))
	done
	((hour++))
done
